version: '3'
services:
    mongodb:
        image: mongo:latest
        container_name: mongo-db
        restart: always
        environment:
            MONGO_INITDB_DATABASE: repository
        ports:
            - 27017:27017
        volumes:
            - ./mongoinit.js:/docker-entrypoint-initdb.d/mongoinit.js:ro
    api:
        image: movies
        ports:
            - 8080:8080
        links:
            - mongodb
